'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LeaderConfirm

    '''<summary>
    '''TxtUnConfDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtUnConfDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnConfUnConfDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfUnConfDate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GrdWaitConf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdWaitConf As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TxtConfDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtConfDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GrdConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrdConfirm As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtEditHour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEditHour As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnUnConfSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnUnConfSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnUnConfDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnUnConfDel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LblInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblShift control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblShift As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DrpShift control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrpShift As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LblHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblHours As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DrpHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrpHours As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LblReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblReason As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DrpReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DrpReason As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BtnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnConfSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnConfDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfDel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TextTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextTest As Global.System.Web.UI.WebControls.TextBox
End Class
