'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Register

    '''<summary>
    '''Regist_EmpNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Regist_EmpNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Txt_Regist_EmpNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Regist_EmpNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Regist_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Regist_Password As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Txt_Regist_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Regist_Password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Regist_Conf_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Regist_Conf_Password As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Txt_Regist_Conf_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Regist_Conf_Password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Rfid_card control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Rfid_card As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtRfid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRfid As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRegister As Global.System.Web.UI.WebControls.Button
End Class
